# This is a basic workflow to help you get started with Actions

name: Compile LESS to CSS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install lessc
        run: npm install -g less
      - name: Clean up old .css files
        run: rm -rf css/*.css
      - name: Compile LESS to CSS
        run: |
          for file in $(ls less); do
            if [[ $file == *.less ]]; then
              lessc less/${file} css/${file%%.*}.css
            fi
          done
      - name: Push compiled CSS
        run: |
          git add -f css/*.css
          git commit -m "GitHub Actions: Compiled LESS to CSS."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
